### PR TITLE
Repository class store implementation and some other minor enhancements on basic repositories

### PR DESCRIPTION
**Pull request by stolsma**
Wanted to implement my own repository type and found out that it was difficult to add one so I added a repository class store with accompanying add, remove and list functions. 

Working on it I also implemented App config checking to be use from all repository classes and I also found some `throw` statements  (instead of using `callback(err)`) that would break haibu if there wasn't a global error handling function.

BTW also added a vows test file and changed the existing tests for the changed error returns.

Hope this is clean enough to be pushed ahead!!

Thanks,

Sander

### CODE REVIEW

**Comment by stolsma** [comment]
One other question !

When looking through the repositories/npm.js code, I observed that when dependencies are being installed on the downloaded/copied code, the dependency list of the given app config is being used instead of dependency list from the package.json file downloaded and copied with the code. (see:  https://github.com/nodejitsu/haibu/blob/master/lib/haibu/repositories/npm.js#L44) 

That means for example that if the downloaded package.json from git has a different dependency list then the one given through the app config the program could run into errors. Is there a reason for this behavior (security mitigation for example?) or is this a bug??

If it is not a bug I would like to request a possible configuration switch to use the config.json dependencies instead of the app configuration dependencies list. And if needed I can add code implementing this to this push request too... ;-)

Thanks!!

**Comment by stolsma** [comment]
Hmm... accidentally pressed the close button... :-(

**Comment by stolsma** [comment]
I added some more tests plus a fix for the new tests because I didn't test good enough :-(

**Comment by stolsma** [comment]
Did some cleaning work on the repository code. Not sure if I could really delete all the functions but tests are ok and haibu is still working at my system... ;-)

Also added npm as a repository type. Not totally happy with it though as the app is being installed in a node_modules/'package name' (that translates to homeDir/'package name') directory instead under homeDir. Although now also the .bin directory is reachable... What do you think: try to get rid of the node_modules directory or not ??

**Comment by stolsma** [comment]
Last commits for repository flexibility, I'm done for now... ;-)

BTW Good luck trying to go live with the Nodejistu hosting service! I hope there are no big problems!!

**Comment by indexzero** [comment]
This is good. I've cherry-picked your commits. In the future it would be nice if you could squash them into one :)

**Comment by stolsma** [comment]
Thanks!!!! Didn't expect beforehand that it would take this amount of time and so many changes ;-) Will do next time!! :-)

**Pull request closed without merging**
