### PR TITLE
[drone] use newly added .stop() callback

### PR DESCRIPTION
**Pull request by indutny**
nt

### CODE REVIEW

**Comment by indutny** [comment]
Should be applied in pair with: indexzero/forever#133

**Comment by indexzero** [comment]
This is correct in program-flow but incorrect in implementation. This is the correct implementation:

``` js
function onStop() {
  app.drones[key].monitor.removeListener('error', onErr);
  results.push(app.drones[key].process);
  self._remove(app, app.drones[key], cleanup, function () {
    next(); 
  });
}

function onErr(err) {
  //
  // Remark should we handle errors here
  //
  app.drones[key].monitor.removeListener('stop', onStop);
}

app.drones[key].monitor.once('stop', onStop);
app.drones[key].monitor.once('error', onErr);
app.drones[key].monitor.stop();
```

**Comment by indutny** [comment]
Can I ask you to review this please? ^

**Comment by indexzero** [comment]
Looks good. I'll merge it in today.

**Comment by indexzero** [comment]
Cherry-picked

**Pull request closed without merging**
