### PR TITLE
Arguments implementation plus tests

### PR DESCRIPTION
**Pull request by stolsma**
Took some time but at last the requested Arguments pass through code... It's incredibly busy here and I had some problems creating the included tests (because of a stupid thing I did wrong... :-( )

What do you think ???

### CODE REVIEW

**Comment by indexzero** [comment]
Looks good. I'll have to merge it into the `flatiron` branch, but should be able to do that tonight.

**Comment by indexzero** [comment]
@stolsma Sorry about not getting back to you sooner on this. I didn't notice the `package.json` API before, but:

``` js
  {
    "scripts": {
      "start": "bin/server",
      "arguments": ["-a", "%w"] 
    }
  }
```

Seems to brittle to me because different arguments could be passed to different scripts. This could break compatibility with `npm`. Could we try:

``` js
  {
    "scripts": {
      "start": {
        "path": "bin/server",
        "arguments": ["-a", "%w"] 
      }
    }
  }
```

Let me know what you think.

**Comment by stolsma** [comment]
Yep, nice idea!! Unfortunately I don't have time to change the current pull request to the current version of Haibu and implement this change... :-( 

Maybe there is someone else who is able to implement this ??

PS: Sorry for the late reply, but hell, this Pull is already open for 7 month eh... ;-)

**Comment by stolsma** [comment]
@indexzero @bmeck At last I have some spare time after 8 months of hard work... ;-)

Want to get arguments implemented and after looking at Issue #98 I came to the conclusion that maybe changing the start option to a string instead of a object will be better for backwards compatibility and for compatibility with NPM. It can then look like for example:

```
  {
    "scripts": {
      "start": "node script.js -p 80 -h %h -a %a -o %c"
    }
  }
```

or:

```
  {
    "scripts": {
      "start": "script.js -p 80 -h %h -a %a -o %c"
    }
  }
```

Where the following options like:
%h will be replaced by process.env.HOME,
%a will be replaced by repo.appDir,
%c will be replaced by repo.homeDir

This can easily implemented but I don't know if this will give problems with the current implementation of 'jitsu' and the running cloud environment. What do you two think ??

**Comment by mmalecki** [comment]
What we should do is spawn `sh -c <whatever>` after making sure that the command is `coffee` or `node`.

**Comment by jfhbrook** [comment]
I'm going to close this PR, since it looks like nobody is happy with this implementation.

My $0.02:
- scripts:start should be more or less compatible with npm's `sh -c` job
- having haibu being able to intelligently pass cli args to the executable is highly desirable
- Instead of %h, %a, %c, etc., use shell vars and define them in the env field of the package.json. For example:

``` json
{
  "scripts": {
    "start": "node script.js -p 80 -h $APP_HOST -a $APP_DIR -o $HOME"
  },
  "env": {
    "APP_HOST": "foo.jit.su",
    "APP_DIR": "./"
  }
}
```

You get the idea. This should also be 100% compatible with npm/sh -c.

**Comment by stolsma** [comment]
Ok, that would be a nice implementation indeed. Will try to make some code but if someone else want to do it... ;-)

**Comment by btford** [comment]
Any progress on this? I'd really like to be able to use the `--harmony` flag.

**Comment by indexzero** [comment]
@btford Not sure if @stolsma has revisited this, but the API proposed by @jesusabdullah is what we are going to go with. If you want to implement it we'll get it rolled out ASAP :)

**Comment by btford** [comment]
Challenge accepted.

**Comment by stolsma** [comment]
@btford @indexzero I'm over my head again in a new project. Didn't have time to write a new implementation so if @btford can write something that would be nice!!! :-)

**Pull request closed without merging**
